heat_template_version: 2013-05-23

resources:
  cinder_volume:
    type: OS::Cinder::Volume
    properties:
      count: {get_param: number_of_servers}
      size: { get_param: volume_size }
      availability_zone: { get_param: availability_zone }
  nova_instance:
    type: OS::Nova::Server
    properties:
      name: my_server_%index%
      count: {get_param: number_of_servers}
      availability_zone: { get_param: availability_zone }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: cinder_volume } 
      instance_uuid: { get_resource: nova_instance }
      mountpoint: /dev/vdc